# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b76b8f13d3f762667d59a2b6c82a1c36a5c90e3e2f42a054a0b54e59d3652bdbe9d1df418f5e15bf35278a90604f742b17469f349a7160067657917ac2f17fce

test:
  secret_key_base: ff29e57fe64e9f75391f5208b5980312ea5c9661e709621a46514da83b056506a306e24f15784ed917727423626356ed514858623dbe6181367ac90ad517bece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
